name: swipolitique
description: A new Flutter project.

version: 2.0+30

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  layoutools:
    git:
      url: https://github.com/yelkamel/layoutools

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_image: ^1.1.1
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5
  get: ^4.6.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/image/
    - assets/fonts/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 600
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900